language: rust

rust:
  - stable
  - beta
  - nightly

branches:
  except:
    - dev
    - benches

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

script:
  - |
      cargo test --features impl_serialize &&
      cargo test --features impl_serialize --release
